### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bladeoflight16** [skeleten/SHN-Editor#4]
Could you add a license file to this code so it's clear what restrictions there are on forking/modifying and redistribution?

**Comment by skeleten** [comment]
I've added the MIT-License to the project. Thank you for actually looking for one though!

**Comment by bladeoflight16** [comment]
Thanks for being so generous with your work. =)

**Comment by skeleten** [comment]
Make no mistake - this is far from being only my work.
The main code base was done by Cedric and since then there have been many contributors. I'm merely hosting the code base on Github at the moment.
